### ISSUE TITLE
S3 Access Denied Error during CloudFormation Template Deployment

### ISSUE THREAD

**Issue by mchittineni** [aws-solutions-library-samples/cloud-intelligence-dashboards-framework#796]
I encountered an S3 Access Denied error while attempting to deploy a CloudFormation template in a source account. Despite following the steps outlined in the [CUDOS](https://catalog.workshops.aws/awscid/en-US/dashboards/foundational/cudos-cid-kpi/deploy) 

I'm able to proceed step 1 without any issues. However, during step 2, when deploying the CloudFormation template, the error persists.

I've made multiple attempts to deploy the CloudFormation template after waiting for a certain period, but the issue persists. Any insights on resolving this would be appreciated.

![Screenshot 2024-04-24 at 12 12 50](https://github.com/aws-samples/aws-cudos-framework-deployment/assets/116578727/13587d7b-9b6a-4e5b-a353-8255cd5c792e)

**Comment by iakov-aws** [comment]
Please make sure you follow the guidance and double check the parameters of the stack

Typically this error happen if the destination bucket in destination account is not yet created (stack not created in source account) or not configured to accept replication from source account (source account is not listed in parameters of the stack)

also prefix parameter should be the same

**Comment by iakov-aws** [comment]
can you confirm that SourceAccountIds is set correctly in the stack of Destination account?

**Comment by iakov-aws** [comment]
please can you write to our feedback email  https://catalog.workshops.aws/awscid/en-US/feedback-support we can set up a quick call to review.
